# Generated by Django 3.2.6 on 2024-01-11 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20230113_2037'),
        ('trabajos', '0002_trabajo_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='lente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lente_trabajo', to='base.lente', verbose_name='Lente'),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='tratamiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tratamiento_trabajo', to='base.tratamiento', verbose_name='Tratamiento'),
        ),
    ]
