# Generated by Django 3.2.6 on 2024-01-11 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0003_auto_20240110_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='detalle',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='detalle_trabajo'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='observacion',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='observacion_trabajo'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='tarea',
            field=models.CharField(blank=True, help_text='Tarea o actividad extra realizada sobre el trabajo', max_length=250, null=True, verbose_name='tarea_trabajo'),
        ),
    ]
