# Generated by Django 3.2.6 on 2024-01-11 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0004_auto_20240110_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trabajo',
            old_name='od_ad',
            new_name='od_add',
        ),
        migrations.RenameField(
            model_name='trabajo',
            old_name='oi_ad',
            new_name='oi_add',
        ),
    ]
