# Generated by Django 3.2.6 on 2024-01-11 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20230113_2037'),
        ('trabajos', '0005_auto_20240110_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='armazon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='armazon_trabajo', to='base.armazon', verbose_name='armazon'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='fecha',
            field=models.DateTimeField(verbose_name='fecha_trabajo'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='lente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lente_trabajo', to='base.lente', verbose_name='Lente'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='lente_con_tratamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lente_con_tratamiento_trabajo', to='base.lentetratamiento', verbose_name='lente_con_tratamiento'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='obra_social',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obra_social_trabajo', to='base.obrasocial', verbose_name='obra_social'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='tratamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tratamiento_trabajo', to='base.tratamiento', verbose_name='Tratamiento'),
        ),
    ]
