# Generated by Django 5.0.3 on 2024-03-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0006_auto_20240111_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='od_add',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='ojo_derecho_adicion'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='od_cerca_cil',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='ojo_derecho_cerca_cilindrico'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='od_cerca_eje',
            field=models.IntegerField(blank=True, null=True, verbose_name='ojo_derecho_cerca_eje'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='od_cerca_esf',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='ojo_derecho_cerca_esferico'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='od_lejos_cil',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='ojo_derecho_lejos_cilindrico'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='od_lejos_eje',
            field=models.IntegerField(blank=True, null=True, verbose_name='ojo_derecho_lejos_eje'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='od_lejos_esf',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='ojo_derecho_lejos_esferico'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='oi_add',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='ojo_izquierdo_adicion'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='oi_cerca_cil',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='ojo_izquierdo_cerca_cilindrico'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='oi_cerca_eje',
            field=models.IntegerField(blank=True, null=True, verbose_name='ojo_izquierdo_cerca_eje'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='oi_cerca_esf',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='ojo_izquierdo_cerca_esferico'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='oi_lejos_cil',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='ojo_izquierdo_lejos_cilindrico'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='oi_lejos_eje',
            field=models.IntegerField(blank=True, null=True, verbose_name='ojo_izquierdo_lejos_eje'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='oi_lejos_esf',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='ojo_izquierdo_lejos_esferico'),
        ),
    ]
