# Generated by Django 5.0.3 on 2024-03-29 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_persona_ciudad_alter_lente_descripcion_and_more'),
        ('trabajos', '0007_alter_trabajo_od_add_alter_trabajo_od_cerca_cil_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajo',
            name='lente',
        ),
        migrations.AddField(
            model_name='trabajo',
            name='lente_od',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lente_od_trabajo', to='base.lente', verbose_name='Lente_od'),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='lente_oi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lente_oi_trabajo', to='base.lente', verbose_name='Lente_oi'),
        ),
    ]
