# Generated by Django 5.0.3 on 2024-03-29 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_persona_ciudad_alter_lente_descripcion_and_more'),
        ('trabajos', '0008_remove_trabajo_lente_trabajo_lente_od_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajo',
            name='lente_od',
        ),
        migrations.RemoveField(
            model_name='trabajo',
            name='lente_oi',
        ),
        migrations.AddField(
            model_name='trabajo',
            name='lente_cerca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lente_cerca_trabajo', to='base.lente', verbose_name='Lente_oi'),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='lente_lejos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lente_lejos_trabajo', to='base.lente', verbose_name='Lente_od'),
        ),
    ]
