# Generated by Django 5.0.3 on 2026-01-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0009_remove_trabajo_lente_od_remove_trabajo_lente_oi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='tipo_lentes',
            field=models.CharField(choices=[('MONO', 'MONOFOCAL'), ('BI-MULTI', 'BIFOCAL-MULTIFOCAL')], default=1, max_length=25),
            preserve_default=False,
        ),
    ]
