# Generated by Django 5.0.3 on 2026-01-15 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_material'),
        ('trabajos', '0010_trabajo_tipo_lentes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajo',
            name='armazon',
        ),
        migrations.RemoveField(
            model_name='trabajo',
            name='lente_cerca',
        ),
        migrations.RemoveField(
            model_name='trabajo',
            name='lente_con_tratamiento',
        ),
        migrations.RemoveField(
            model_name='trabajo',
            name='lente_lejos',
        ),
        migrations.RemoveField(
            model_name='trabajo',
            name='tipo_lentes',
        ),
        migrations.RemoveField(
            model_name='trabajo',
            name='tratamiento',
        ),
        migrations.AddField(
            model_name='trabajo',
            name='tipo_trabajo',
            field=models.CharField(choices=[('MONO', 'Monofocal'), ('BI', 'Bifocal'), ('MULTI', 'Multifocal'), ('1/2', 'Ocupacional')], default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TrabajoArmazon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('UNICO', 'UNICO'), ('LEJOS', 'LEJOS'), ('CERCA', 'CERCA')], max_length=25)),
                ('armazon', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='TrabajoArmazon_armazon', to='base.armazon')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='TrabajoArmazon_trabajo', to='trabajos.trabajo')),
            ],
        ),
        migrations.AddField(
            model_name='trabajo',
            name='armazones',
            field=models.ManyToManyField(related_name='trabajo_armazon', through='trabajos.TrabajoArmazon', to='base.armazon'),
        ),
        migrations.CreateModel(
            name='TrabajoLente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('UNICO', 'UNICO'), ('LEJOS', 'LEJOS'), ('CERCA', 'CERCA')], max_length=25)),
                ('lente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='TrabajoLente_lente', to='base.lente')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='TrabajoLente_trabajo', to='trabajos.trabajo')),
            ],
        ),
        migrations.AddField(
            model_name='trabajo',
            name='lentes',
            field=models.ManyToManyField(related_name='trabajo_lente', through='trabajos.TrabajoLente', to='base.lente'),
        ),
        migrations.CreateModel(
            name='TrabajoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('UNICO', 'UNICO'), ('LEJOS', 'LEJOS'), ('CERCA', 'CERCA')], max_length=25)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='TrabajoMaterial_armazon', to='base.material')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='TrabajoMaterial_trabajo', to='trabajos.trabajo')),
            ],
        ),
        migrations.AddField(
            model_name='trabajo',
            name='materiales',
            field=models.ManyToManyField(related_name='trabajo_material', through='trabajos.TrabajoMaterial', to='base.material'),
        ),
        migrations.CreateModel(
            name='TrabajoTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('UNICO', 'UNICO'), ('LEJOS', 'LEJOS'), ('CERCA', 'CERCA')], max_length=25)),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='TrabajoTratamiento_trabajo', to='trabajos.trabajo')),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='TrabajoTratamiento_tratamiento', to='base.tratamiento')),
            ],
        ),
        migrations.AddField(
            model_name='trabajo',
            name='tratamientos',
            field=models.ManyToManyField(related_name='trabajo_tratamiento', through='trabajos.TrabajoTratamiento', to='base.tratamiento'),
        ),
    ]
