# Generated by Django 5.0.3 on 2026-01-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0011_remove_trabajo_armazon_remove_trabajo_lente_cerca_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trabajo',
            old_name='fecha',
            new_name='fecha_alta',
        ),
        migrations.AddField(
            model_name='trabajo',
            name='fecha_trabajo',
            field=models.DateField(null=True, verbose_name='fecha_trabajo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='fecha_receta',
            field=models.DateField(null=True, verbose_name='fecha_receta'),
        ),
        migrations.AlterField(
            model_name='trabajolente',
            name='tipo',
            field=models.CharField(choices=[('UNICO', 'UNICO'), ('LEJOS', 'LEJOS'), ('CERCA', 'CERCA')], max_length=25, verbose_name='tipo_lente'),
        ),
    ]
