# Generated by Django 5.0.3 on 2026-01-22 19:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0012_rename_fecha_trabajo_fecha_alta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='fecha_alta',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha_alta'),
        ),
    ]
