# Generated by Django 5.0.3 on 2026-01-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0013_alter_trabajo_fecha_alta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='fecha_trabajo',
            field=models.DateField(verbose_name='fecha_trabajo'),
        ),
    ]
