# Generated by Django 5.0.3 on 2024-03-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20230113_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='localidad'),
        ),
        migrations.AlterField(
            model_name='lente',
            name='descripcion',
            field=models.CharField(max_length=60, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='obrasocial',
            name='descripcion',
            field=models.CharField(max_length=60, verbose_name='Nombre'),
        ),
    ]
