# Generated by Django 5.0.3 on 2026-01-05 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_persona_ciudad_alter_lente_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='obra_social',
        ),
        migrations.AddField(
            model_name='persona',
            name='obras_sociales',
            field=models.ManyToManyField(null=True, related_name='personas', to='base.obrasocial', verbose_name='Obras Sociales'),
        ),
        migrations.AlterField(
            model_name='lentetratamiento',
            name='tratamiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tratamiento_lenteTramamiento', to='base.tratamiento', verbose_name='tratamiento'),
        ),
    ]
