# Generated by Django 5.0.3 on 2026-01-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_persona_obra_social_persona_obras_sociales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='observacion',
            field=models.CharField(max_length=250, null=True, verbose_name='observaciones'),
        ),
        migrations.AddField(
            model_name='persona',
            name='tel3',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='telefono_3'),
        ),
    ]
