# Generated by Django 5.0.3 on 2026-01-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_persona_observacion_persona_tel3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='obras_sociales',
            field=models.ManyToManyField(related_name='personas', to='base.obrasocial', verbose_name='Obras Sociales'),
        ),
    ]
