# Generated by Django 5.0.3 on 2026-01-07 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_persona_obras_sociales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='observacion',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='observaciones'),
        ),
    ]
