# Generated by Django 5.0.3 on 2026-01-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_persona_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='obras_sociales',
            field=models.ManyToManyField(blank=True, related_name='personas', to='base.obrasocial', verbose_name='Obras Sociales'),
        ),
    ]
