# Generated by Django 5.0.3 on 2026-01-22 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_material'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='armazon',
            options={'ordering': ['descripcion'], 'verbose_name': 'Armazon', 'verbose_name_plural': 'Armazones'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Doctor', 'verbose_name_plural': 'Doctores'},
        ),
        migrations.AlterModelOptions(
            name='lente',
            options={'ordering': ['descripcion'], 'verbose_name': 'Lente', 'verbose_name_plural': 'Lentes'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['descripcion'], 'verbose_name': 'Material', 'verbose_name_plural': 'Materiales'},
        ),
        migrations.AlterModelOptions(
            name='obrasocial',
            options={'ordering': ['descripcion'], 'verbose_name': 'Obra Social', 'verbose_name_plural': 'Obras Sociales'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['descripcion'], 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='tratamiento',
            options={'ordering': ['descripcion'], 'verbose_name': 'Tratamiento', 'verbose_name_plural': 'Tratamientos'},
        ),
    ]
